[package]
name = "agora-server"
description = "Exchange server binary: composition root"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[[bin]]
name = "agora-server"
path = "src/main.rs"

[dependencies]
agora-api = { workspace = true }
agora-runtime = { workspace = true }
agora-telemetry = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
mimalloc = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]


[lints]
workspace = true
